language: node_js

notifications:
  email: false

node_js:
  - "10.15.3"

install: npm install

jobs:
  include:
    - stage: Tests
      script:
        - npm run lint
        - npm run test:coverage
        - npm run test:coveralls

cache:
  directories:
    - node_modules