language: node_js

notifications:
  email: false

  node_js:
  - "10.15.3"

install: npm install

jobs:
  include:
    - stage: "Tests"
      script: npm test
      script: npm run lint

after_success: "npm run test:coverage"

cache:
  directories:
    - node_modules